### ISSUE TITLE
Updates for bevy 0.11?

### ISSUE THREAD

**Issue by lislis** [hideakitai/bevy_serial#1]
Hey there! I would like to use your plugin to read Serial data from an Arduino-based controller.
Sadly I can't add bevy-serial currently because of version conflicts which I think stem from out-of-date dependencies. And the bevy APIs  have changed quite a lot, too.
Do you think you will update this project again?

**Comment by hideakitai** [comment]
Yes, I will soon ;)

**Comment by hideakitai** [comment]
✅ Done
