### ISSUE TITLE
Provide an escape hatch for error handling in read_serial and write_serial

### ISSUE THREAD

**Issue by iancormac84** [hideakitai/bevy_serial#7]
Lines [337](https://github.com/hideakitai/bevy_serial/blob/18e09684c73398b357d2713a653a9ce7ebee0e80/src/lib.rs#L337) and [391](https://github.com/hideakitai/bevy_serial/blob/18e09684c73398b357d2713a653a9ce7ebee0e80/src/lib.rs#L391) simply print out the error that was triggered. Unfortunately, this causes an infinite loop if an error gets triggered. Perhaps it would be good to allow users of the plugin to configure what would happen if their running program encountered this scenario. Thoughts?

**Comment by hideakitai** [comment]
Thank you for your suggestion; it's a great point. I think the following are good to implement. What do you think?

- Register an error handler with error code
- Return error from system (if it can)

**Comment by iancormac84** [comment]
Yes, those sound good! Bevy provides the [pipe](https://docs.rs/bevy/latest/bevy/prelude/trait.IntoSystem.html#method.pipe) method that allows a system to take the output of another system and handle it. I was attempting to use this, but I haven't had any luck.

**Comment by hideakitai** [comment]
@iancormac84 [v0.6.0](https://github.com/hideakitai/bevy_serial/releases/tag/v0.6.0) supports [registering user handlers](https://github.com/hideakitai/bevy_serial/blob/045ae4421781201f8c7a106be2460d21b528d9d1/examples/configuration.rs#L30-L35) for read/write results (not only error). It will be published to cargo in a few hours. Please try it.
